print("-" * 40)
print("HelloWorld! THis is DevOps Pipeline Success.")
print("The App is running inside a Docker Container, and its a sucess.")
print("I am adding one more line to this python file")
print("-" * 40)
